feat: add stream_href method
stac-utils/stac-asset pull request #123
Opened 2023-11-17 23:52 UTC by jkeifer

## Related issues and pull requests

- n/a

## Description

I have a case where I am using `read_href`, but can significantly decrease memory usage if I use the chunks as they are downloaded rather than waiting for the the complete byte stream from `read_href`. Seeing that `read_href` is concatenating a stream, this change simply splits the chunked downloading from `read_href` into a new method `stream_href`, which `read_href` uses internally.

## Checklist

- [x] Add tests
- [x] Add docs
- [x] Update CHANGELOG

2023-11-18 23:55 UTC, jkeifer commented
Actually, I may have jumped the gun on this one. If it isn't something that you want to support as part of the public API without a solid use-case then please leave this unmerged for a short while until I re-confirm the need.

2023-11-21 12:53 UTC, gadomski requested changes
In addition to the name change, we should also add a `stac_asset.blocking.open_href`.

2023-11-21 12:53 UTC, gadomski commented on src/stac_asset/_functions.py
> +async def stream_href(
I think this should be named `open_href` to align with the [`Client` method](https://stac-asset.readthedocs.io/en/latest/api.html#stac_asset.Client.open_href).

2023-11-21 17:08 UTC, jkeifer commented
I'm not sure there's a particularly elegant way to make a blocking version of `open_href`. The fundamental problem is `asyncio.run()` will synchronously execute a coroutine, but `open_href` is different in that it is returning an `AsyncIterable` which itself needs to be, well, asynchronously iterated. As far as I understand it, you can't do async iteration without running in an event loop.

I did find a snippet on SO that shows how to do this: https://stackoverflow.com/a/55164899. I don't know how you feel about it, but I wouldn't want to maintain something like that in this lib--if a user _really_ needs to use `open_href` in sync code I would say they can take on a solution like that.

2023-11-21 18:30 UTC, gadomski commented
Nope, makes a lot of sense, thanks for pointing that out.

2023-11-21 18:30 UTC, gadomski approved these changes

2023-11-21 18:31 UTC, merged